name: xlinecargo
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  postgres: ^2.6.3
  dart_jsonwebtoken: ^2.8.2
  bcrypt: ^1.1.3
  path: ^1.9.0
  shelf_swagger_ui: ^2.0.0


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
